services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    restart: always
    environment:
      - MONGO_URI=mongodb://db_mongo:27017/your_database_name
    depends_on:
      - db_mongo
    volumes:
      - ./logs:/app/logs
      - ./public:/app/public

  db_mongo:
    image: mongo:latest
    container_name: mongo_database
    restart: always
    volumes:
      - database-data:/data/db
    expose:
      - 27017

volumes:
  database-data:
